/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ANPRLog {
  'status' : ANPRLogStatus,
  'organizationId' : bigint,
  'vehicleType' : VehicleType,
  'confidenceScore' : bigint,
  'plateNumber' : string,
  'timestamp' : Time,
  'locationName' : string,
  'cameraId' : bigint,
}
export type ANPRLogStatus = { 'alert' : null } |
  { 'whitelisted' : null } |
  { 'identified' : null };
export interface Alert {
  'organizationId' : bigint,
  'alertType' : AlertType,
  'acknowledged' : boolean,
  'triggeredAt' : Time,
  'plateNumber' : string,
  'message' : string,
  'severity' : AlertSeverity,
  'cameraId' : bigint,
}
export type AlertSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type AlertType = { 'blacklist' : null } |
  { 'whitelist' : null } |
  { 'overspeed' : null };
export interface Camera {
  'fps' : bigint,
  'status' : CameraStatus,
  'organizationId' : bigint,
  'name' : string,
  'latencyMs' : bigint,
  'addedAt' : Time,
  'cameraType' : CameraType,
  'location' : string,
  'bitrate' : bigint,
}
export type CameraStatus = { 'offline' : null } |
  { 'recording' : null } |
  { 'online' : null };
export type CameraType = { 'onvif' : null } |
  { 'rtsp' : null } |
  { 'hikvision' : null };
export interface Organization {
  'apiCallsUsed' : bigint,
  'name' : string,
  'createdAt' : Time,
  'plan' : OrganizationPlan,
  'cameraLimit' : bigint,
  'apiCallsLimit' : bigint,
}
export type OrganizationPlan = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'free' : null };
export type Time = bigint;
export interface UserProfile {
  'organizationId' : [] | [bigint],
  'name' : string,
}
export interface UserRole {
  'organizationId' : bigint,
  'permissions' : Array<string>,
  'userId' : Principal,
  'role' : UserRoleType,
}
export type UserRoleType = { 'admin' : null } |
  { 'operator' : null } |
  { 'viewer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleType = { 'bus' : null } |
  { 'car' : null } |
  { 'truck' : null } |
  { 'motorcycle' : null } |
  { 'other' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeAlert' : ActorMethod<[bigint], undefined>,
  'addANPRLog' : ActorMethod<[ANPRLog], bigint>,
  'addAlert' : ActorMethod<[Alert], bigint>,
  'addCamera' : ActorMethod<[Camera], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignUserRole' : ActorMethod<[UserRole], undefined>,
  'createOrganization' : ActorMethod<[Organization], bigint>,
  'getANPRLogsByOrganization' : ActorMethod<[bigint], Array<ANPRLog>>,
  'getAlertsByOrganization' : ActorMethod<[bigint], Array<Alert>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCamerasByOrganization' : ActorMethod<[bigint], Array<Camera>>,
  'getOrganization' : ActorMethod<[bigint], Organization>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], [] | [UserRole]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCamera' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'updateCamera' : ActorMethod<[bigint, Camera], undefined>,
  'updateOrganizationPlan' : ActorMethod<[bigint, OrganizationPlan], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];