/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ANPRLogStatus = IDL.Variant({
  'alert' : IDL.Null,
  'whitelisted' : IDL.Null,
  'identified' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'bus' : IDL.Null,
  'car' : IDL.Null,
  'truck' : IDL.Null,
  'motorcycle' : IDL.Null,
  'other' : IDL.Null,
});
export const Time = IDL.Int;
export const ANPRLog = IDL.Record({
  'status' : ANPRLogStatus,
  'organizationId' : IDL.Nat,
  'vehicleType' : VehicleType,
  'confidenceScore' : IDL.Nat,
  'plateNumber' : IDL.Text,
  'timestamp' : Time,
  'locationName' : IDL.Text,
  'cameraId' : IDL.Nat,
});
export const AlertType = IDL.Variant({
  'blacklist' : IDL.Null,
  'whitelist' : IDL.Null,
  'overspeed' : IDL.Null,
});
export const AlertSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const Alert = IDL.Record({
  'organizationId' : IDL.Nat,
  'alertType' : AlertType,
  'acknowledged' : IDL.Bool,
  'triggeredAt' : Time,
  'plateNumber' : IDL.Text,
  'message' : IDL.Text,
  'severity' : AlertSeverity,
  'cameraId' : IDL.Nat,
});
export const CameraStatus = IDL.Variant({
  'offline' : IDL.Null,
  'recording' : IDL.Null,
  'online' : IDL.Null,
});
export const CameraType = IDL.Variant({
  'onvif' : IDL.Null,
  'rtsp' : IDL.Null,
  'hikvision' : IDL.Null,
});
export const Camera = IDL.Record({
  'fps' : IDL.Nat,
  'status' : CameraStatus,
  'organizationId' : IDL.Nat,
  'name' : IDL.Text,
  'latencyMs' : IDL.Nat,
  'addedAt' : Time,
  'cameraType' : CameraType,
  'location' : IDL.Text,
  'bitrate' : IDL.Nat,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRoleType = IDL.Variant({
  'admin' : IDL.Null,
  'operator' : IDL.Null,
  'viewer' : IDL.Null,
});
export const UserRole = IDL.Record({
  'organizationId' : IDL.Nat,
  'permissions' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'role' : UserRoleType,
});
export const OrganizationPlan = IDL.Variant({
  'pro' : IDL.Null,
  'enterprise' : IDL.Null,
  'free' : IDL.Null,
});
export const Organization = IDL.Record({
  'apiCallsUsed' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'plan' : OrganizationPlan,
  'cameraLimit' : IDL.Nat,
  'apiCallsLimit' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'organizationId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
  'addANPRLog' : IDL.Func([ANPRLog], [IDL.Nat], []),
  'addAlert' : IDL.Func([Alert], [IDL.Nat], []),
  'addCamera' : IDL.Func([Camera], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignUserRole' : IDL.Func([UserRole], [], []),
  'createOrganization' : IDL.Func([Organization], [IDL.Nat], []),
  'getANPRLogsByOrganization' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ANPRLog)],
      ['query'],
    ),
  'getAlertsByOrganization' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCamerasByOrganization' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Camera)],
      ['query'],
    ),
  'getOrganization' : IDL.Func([IDL.Nat], [Organization], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCamera' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'updateCamera' : IDL.Func([IDL.Nat, Camera], [], []),
  'updateOrganizationPlan' : IDL.Func([IDL.Nat, OrganizationPlan], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ANPRLogStatus = IDL.Variant({
    'alert' : IDL.Null,
    'whitelisted' : IDL.Null,
    'identified' : IDL.Null,
  });
  const VehicleType = IDL.Variant({
    'bus' : IDL.Null,
    'car' : IDL.Null,
    'truck' : IDL.Null,
    'motorcycle' : IDL.Null,
    'other' : IDL.Null,
  });
  const Time = IDL.Int;
  const ANPRLog = IDL.Record({
    'status' : ANPRLogStatus,
    'organizationId' : IDL.Nat,
    'vehicleType' : VehicleType,
    'confidenceScore' : IDL.Nat,
    'plateNumber' : IDL.Text,
    'timestamp' : Time,
    'locationName' : IDL.Text,
    'cameraId' : IDL.Nat,
  });
  const AlertType = IDL.Variant({
    'blacklist' : IDL.Null,
    'whitelist' : IDL.Null,
    'overspeed' : IDL.Null,
  });
  const AlertSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Alert = IDL.Record({
    'organizationId' : IDL.Nat,
    'alertType' : AlertType,
    'acknowledged' : IDL.Bool,
    'triggeredAt' : Time,
    'plateNumber' : IDL.Text,
    'message' : IDL.Text,
    'severity' : AlertSeverity,
    'cameraId' : IDL.Nat,
  });
  const CameraStatus = IDL.Variant({
    'offline' : IDL.Null,
    'recording' : IDL.Null,
    'online' : IDL.Null,
  });
  const CameraType = IDL.Variant({
    'onvif' : IDL.Null,
    'rtsp' : IDL.Null,
    'hikvision' : IDL.Null,
  });
  const Camera = IDL.Record({
    'fps' : IDL.Nat,
    'status' : CameraStatus,
    'organizationId' : IDL.Nat,
    'name' : IDL.Text,
    'latencyMs' : IDL.Nat,
    'addedAt' : Time,
    'cameraType' : CameraType,
    'location' : IDL.Text,
    'bitrate' : IDL.Nat,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRoleType = IDL.Variant({
    'admin' : IDL.Null,
    'operator' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const UserRole = IDL.Record({
    'organizationId' : IDL.Nat,
    'permissions' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'role' : UserRoleType,
  });
  const OrganizationPlan = IDL.Variant({
    'pro' : IDL.Null,
    'enterprise' : IDL.Null,
    'free' : IDL.Null,
  });
  const Organization = IDL.Record({
    'apiCallsUsed' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'plan' : OrganizationPlan,
    'cameraLimit' : IDL.Nat,
    'apiCallsLimit' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'organizationId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeAlert' : IDL.Func([IDL.Nat], [], []),
    'addANPRLog' : IDL.Func([ANPRLog], [IDL.Nat], []),
    'addAlert' : IDL.Func([Alert], [IDL.Nat], []),
    'addCamera' : IDL.Func([Camera], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignUserRole' : IDL.Func([UserRole], [], []),
    'createOrganization' : IDL.Func([Organization], [IDL.Nat], []),
    'getANPRLogsByOrganization' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ANPRLog)],
        ['query'],
      ),
    'getAlertsByOrganization' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Alert)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCamerasByOrganization' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Camera)],
        ['query'],
      ),
    'getOrganization' : IDL.Func([IDL.Nat], [Organization], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCamera' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'updateCamera' : IDL.Func([IDL.Nat, Camera], [], []),
    'updateOrganizationPlan' : IDL.Func([IDL.Nat, OrganizationPlan], [], []),
  });
};

export const init = ({ IDL }) => { return []; };