/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface UserRole {
    organizationId: bigint;
    permissions: Array<string>;
    userId: Principal;
    role: UserRoleType;
}
export interface ANPRLog {
    status: ANPRLogStatus;
    organizationId: bigint;
    vehicleType: VehicleType;
    confidenceScore: bigint;
    plateNumber: string;
    timestamp: Time;
    locationName: string;
    cameraId: bigint;
}
export interface Camera {
    fps: bigint;
    status: CameraStatus;
    organizationId: bigint;
    name: string;
    latencyMs: bigint;
    addedAt: Time;
    cameraType: CameraType;
    location: string;
    bitrate: bigint;
}
export interface Alert {
    organizationId: bigint;
    alertType: AlertType;
    acknowledged: boolean;
    triggeredAt: Time;
    plateNumber: string;
    message: string;
    severity: AlertSeverity;
    cameraId: bigint;
}
export interface Organization {
    apiCallsUsed: bigint;
    name: string;
    createdAt: Time;
    plan: OrganizationPlan;
    cameraLimit: bigint;
    apiCallsLimit: bigint;
}
export interface UserProfile {
    organizationId?: bigint;
    name: string;
}
export enum ANPRLogStatus {
    alert = "alert",
    whitelisted = "whitelisted",
    identified = "identified"
}
export enum AlertSeverity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum AlertType {
    blacklist = "blacklist",
    whitelist = "whitelist",
    overspeed = "overspeed"
}
export enum CameraStatus {
    offline = "offline",
    recording = "recording",
    online = "online"
}
export enum CameraType {
    onvif = "onvif",
    rtsp = "rtsp",
    hikvision = "hikvision"
}
export enum OrganizationPlan {
    pro = "pro",
    enterprise = "enterprise",
    free = "free"
}
export enum UserRoleType {
    admin = "admin",
    operator = "operator",
    viewer = "viewer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleType {
    bus = "bus",
    car = "car",
    truck = "truck",
    motorcycle = "motorcycle",
    other = "other"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acknowledgeAlert(id: bigint): Promise<void>;
    addANPRLog(log: ANPRLog): Promise<bigint>;
    addAlert(alert: Alert): Promise<bigint>;
    addCamera(camera: Camera): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignUserRole(userRole: UserRole): Promise<void>;
    createOrganization(org: Organization): Promise<bigint>;
    getANPRLogsByOrganization(organizationId: bigint): Promise<Array<ANPRLog>>;
    getAlertsByOrganization(organizationId: bigint): Promise<Array<Alert>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCamerasByOrganization(organizationId: bigint): Promise<Array<Camera>>;
    getOrganization(id: bigint): Promise<Organization>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRole(userId: Principal): Promise<UserRole | null>;
    isCallerAdmin(): Promise<boolean>;
    removeCamera(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedDemoData(): Promise<void>;
    updateCamera(id: bigint, camera: Camera): Promise<void>;
    updateOrganizationPlan(id: bigint, plan: OrganizationPlan): Promise<void>;
}
import type { ANPRLog as _ANPRLog, ANPRLogStatus as _ANPRLogStatus, Alert as _Alert, AlertSeverity as _AlertSeverity, AlertType as _AlertType, Camera as _Camera, CameraStatus as _CameraStatus, CameraType as _CameraType, Organization as _Organization, OrganizationPlan as _OrganizationPlan, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRoleType as _UserRoleType, UserRole__1 as _UserRole__1, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acknowledgeAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async addANPRLog(arg0: ANPRLog): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addANPRLog(to_candid_ANPRLog_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addANPRLog(to_candid_ANPRLog_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addAlert(arg0: Alert): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlert(to_candid_Alert_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlert(to_candid_Alert_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCamera(arg0: Camera): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCamera(to_candid_Camera_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCamera(to_candid_Camera_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserRole(arg0: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserRole(to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserRole(to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrganization(arg0: Organization): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrganization(to_candid_Organization_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrganization(to_candid_Organization_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getANPRLogsByOrganization(arg0: bigint): Promise<Array<ANPRLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getANPRLogsByOrganization(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getANPRLogsByOrganization(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlertsByOrganization(arg0: bigint): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertsByOrganization(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertsByOrganization(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCamerasByOrganization(arg0: bigint): Promise<Array<Camera>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCamerasByOrganization(arg0);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCamerasByOrganization(arg0);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganization(arg0: bigint): Promise<Organization> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganization(arg0);
                return from_candid_Organization_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganization(arg0);
            return from_candid_Organization_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeCamera(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCamera(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCamera(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedDemoData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoData();
            return result;
        }
    }
    async updateCamera(arg0: bigint, arg1: Camera): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCamera(arg0, to_candid_Camera_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCamera(arg0, to_candid_Camera_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrganizationPlan(arg0: bigint, arg1: OrganizationPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrganizationPlan(arg0, to_candid_OrganizationPlan_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrganizationPlan(arg0, to_candid_OrganizationPlan_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ANPRLogStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ANPRLogStatus): ANPRLogStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ANPRLog_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ANPRLog): ANPRLog {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_AlertSeverity_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_AlertType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Alert_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_CameraStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CameraStatus): CameraStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_CameraType_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CameraType): CameraType {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Camera_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Camera): Camera {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_OrganizationPlan_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrganizationPlan): OrganizationPlan {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Organization_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Organization): Organization {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserRoleType_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRoleType): UserRoleType {
    return from_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n61(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ANPRLogStatus;
    organizationId: bigint;
    vehicleType: _VehicleType;
    confidenceScore: bigint;
    plateNumber: string;
    timestamp: _Time;
    locationName: string;
    cameraId: bigint;
}): {
    status: ANPRLogStatus;
    organizationId: bigint;
    vehicleType: VehicleType;
    confidenceScore: bigint;
    plateNumber: string;
    timestamp: Time;
    locationName: string;
    cameraId: bigint;
} {
    return {
        status: from_candid_ANPRLogStatus_n32(_uploadFile, _downloadFile, value.status),
        organizationId: value.organizationId,
        vehicleType: from_candid_VehicleType_n34(_uploadFile, _downloadFile, value.vehicleType),
        confidenceScore: value.confidenceScore,
        plateNumber: value.plateNumber,
        timestamp: value.timestamp,
        locationName: value.locationName,
        cameraId: value.cameraId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationId: bigint;
    alertType: _AlertType;
    acknowledged: boolean;
    triggeredAt: _Time;
    plateNumber: string;
    message: string;
    severity: _AlertSeverity;
    cameraId: bigint;
}): {
    organizationId: bigint;
    alertType: AlertType;
    acknowledged: boolean;
    triggeredAt: Time;
    plateNumber: string;
    message: string;
    severity: AlertSeverity;
    cameraId: bigint;
} {
    return {
        organizationId: value.organizationId,
        alertType: from_candid_AlertType_n39(_uploadFile, _downloadFile, value.alertType),
        acknowledged: value.acknowledged,
        triggeredAt: value.triggeredAt,
        plateNumber: value.plateNumber,
        message: value.message,
        severity: from_candid_AlertSeverity_n41(_uploadFile, _downloadFile, value.severity),
        cameraId: value.cameraId
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationId: [] | [bigint];
    name: string;
}): {
    organizationId?: bigint;
    name: string;
} {
    return {
        organizationId: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.organizationId)),
        name: value.name
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fps: bigint;
    status: _CameraStatus;
    organizationId: bigint;
    name: string;
    latencyMs: bigint;
    addedAt: _Time;
    cameraType: _CameraType;
    location: string;
    bitrate: bigint;
}): {
    fps: bigint;
    status: CameraStatus;
    organizationId: bigint;
    name: string;
    latencyMs: bigint;
    addedAt: Time;
    cameraType: CameraType;
    location: string;
    bitrate: bigint;
} {
    return {
        fps: value.fps,
        status: from_candid_CameraStatus_n52(_uploadFile, _downloadFile, value.status),
        organizationId: value.organizationId,
        name: value.name,
        latencyMs: value.latencyMs,
        addedAt: value.addedAt,
        cameraType: from_candid_CameraType_n54(_uploadFile, _downloadFile, value.cameraType),
        location: value.location,
        bitrate: value.bitrate
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    apiCallsUsed: bigint;
    name: string;
    createdAt: _Time;
    plan: _OrganizationPlan;
    cameraLimit: bigint;
    apiCallsLimit: bigint;
}): {
    apiCallsUsed: bigint;
    name: string;
    createdAt: Time;
    plan: OrganizationPlan;
    cameraLimit: bigint;
    apiCallsLimit: bigint;
} {
    return {
        apiCallsUsed: value.apiCallsUsed,
        name: value.name,
        createdAt: value.createdAt,
        plan: from_candid_OrganizationPlan_n58(_uploadFile, _downloadFile, value.plan),
        cameraLimit: value.cameraLimit,
        apiCallsLimit: value.apiCallsLimit
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationId: bigint;
    permissions: Array<string>;
    userId: Principal;
    role: _UserRoleType;
}): {
    organizationId: bigint;
    permissions: Array<string>;
    userId: Principal;
    role: UserRoleType;
} {
    return {
        organizationId: value.organizationId,
        permissions: value.permissions,
        userId: value.userId,
        role: from_candid_UserRoleType_n63(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alert: null;
} | {
    whitelisted: null;
} | {
    identified: null;
}): ANPRLogStatus {
    return "alert" in value ? ANPRLogStatus.alert : "whitelisted" in value ? ANPRLogStatus.whitelisted : "identified" in value ? ANPRLogStatus.identified : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bus: null;
} | {
    car: null;
} | {
    truck: null;
} | {
    motorcycle: null;
} | {
    other: null;
}): VehicleType {
    return "bus" in value ? VehicleType.bus : "car" in value ? VehicleType.car : "truck" in value ? VehicleType.truck : "motorcycle" in value ? VehicleType.motorcycle : "other" in value ? VehicleType.other : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blacklist: null;
} | {
    whitelist: null;
} | {
    overspeed: null;
}): AlertType {
    return "blacklist" in value ? AlertType.blacklist : "whitelist" in value ? AlertType.whitelist : "overspeed" in value ? AlertType.overspeed : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): AlertSeverity {
    return "low" in value ? AlertSeverity.low : "high" in value ? AlertSeverity.high : "critical" in value ? AlertSeverity.critical : "medium" in value ? AlertSeverity.medium : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offline: null;
} | {
    recording: null;
} | {
    online: null;
}): CameraStatus {
    return "offline" in value ? CameraStatus.offline : "recording" in value ? CameraStatus.recording : "online" in value ? CameraStatus.online : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onvif: null;
} | {
    rtsp: null;
} | {
    hikvision: null;
}): CameraType {
    return "onvif" in value ? CameraType.onvif : "rtsp" in value ? CameraType.rtsp : "hikvision" in value ? CameraType.hikvision : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    enterprise: null;
} | {
    free: null;
}): OrganizationPlan {
    return "pro" in value ? OrganizationPlan.pro : "enterprise" in value ? OrganizationPlan.enterprise : "free" in value ? OrganizationPlan.free : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    operator: null;
} | {
    viewer: null;
}): UserRoleType {
    return "admin" in value ? UserRoleType.admin : "operator" in value ? UserRoleType.operator : "viewer" in value ? UserRoleType.viewer : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ANPRLog>): Array<ANPRLog> {
    return value.map((x)=>from_candid_ANPRLog_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Camera>): Array<Camera> {
    return value.map((x)=>from_candid_Camera_n50(_uploadFile, _downloadFile, x));
}
function to_candid_ANPRLogStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ANPRLogStatus): _ANPRLogStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ANPRLog_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ANPRLog): _ANPRLog {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AlertSeverity_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): _AlertSeverity {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_AlertType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): _AlertType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Alert_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Alert): _Alert {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CameraStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CameraStatus): _CameraStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_CameraType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CameraType): _CameraType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Camera_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Camera): _Camera {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_OrganizationPlan_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrganizationPlan): _OrganizationPlan {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_Organization_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Organization): _Organization {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_UserRoleType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRoleType): _UserRoleType {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fps: bigint;
    status: CameraStatus;
    organizationId: bigint;
    name: string;
    latencyMs: bigint;
    addedAt: Time;
    cameraType: CameraType;
    location: string;
    bitrate: bigint;
}): {
    fps: bigint;
    status: _CameraStatus;
    organizationId: bigint;
    name: string;
    latencyMs: bigint;
    addedAt: _Time;
    cameraType: _CameraType;
    location: string;
    bitrate: bigint;
} {
    return {
        fps: value.fps,
        status: to_candid_CameraStatus_n15(_uploadFile, _downloadFile, value.status),
        organizationId: value.organizationId,
        name: value.name,
        latencyMs: value.latencyMs,
        addedAt: value.addedAt,
        cameraType: to_candid_CameraType_n17(_uploadFile, _downloadFile, value.cameraType),
        location: value.location,
        bitrate: value.bitrate
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ANPRLogStatus;
    organizationId: bigint;
    vehicleType: VehicleType;
    confidenceScore: bigint;
    plateNumber: string;
    timestamp: Time;
    locationName: string;
    cameraId: bigint;
}): {
    status: _ANPRLogStatus;
    organizationId: bigint;
    vehicleType: _VehicleType;
    confidenceScore: bigint;
    plateNumber: string;
    timestamp: _Time;
    locationName: string;
    cameraId: bigint;
} {
    return {
        status: to_candid_ANPRLogStatus_n3(_uploadFile, _downloadFile, value.status),
        organizationId: value.organizationId,
        vehicleType: to_candid_VehicleType_n5(_uploadFile, _downloadFile, value.vehicleType),
        confidenceScore: value.confidenceScore,
        plateNumber: value.plateNumber,
        timestamp: value.timestamp,
        locationName: value.locationName,
        cameraId: value.cameraId
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationId: bigint;
    permissions: Array<string>;
    userId: Principal;
    role: UserRoleType;
}): {
    organizationId: bigint;
    permissions: Array<string>;
    userId: Principal;
    role: _UserRoleType;
} {
    return {
        organizationId: value.organizationId,
        permissions: value.permissions,
        userId: value.userId,
        role: to_candid_UserRoleType_n23(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    apiCallsUsed: bigint;
    name: string;
    createdAt: Time;
    plan: OrganizationPlan;
    cameraLimit: bigint;
    apiCallsLimit: bigint;
}): {
    apiCallsUsed: bigint;
    name: string;
    createdAt: _Time;
    plan: _OrganizationPlan;
    cameraLimit: bigint;
    apiCallsLimit: bigint;
} {
    return {
        apiCallsUsed: value.apiCallsUsed,
        name: value.name,
        createdAt: value.createdAt,
        plan: to_candid_OrganizationPlan_n27(_uploadFile, _downloadFile, value.plan),
        cameraLimit: value.cameraLimit,
        apiCallsLimit: value.apiCallsLimit
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationId?: bigint;
    name: string;
}): {
    organizationId: [] | [bigint];
    name: string;
} {
    return {
        organizationId: value.organizationId ? candid_some(value.organizationId) : candid_none(),
        name: value.name
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    organizationId: bigint;
    alertType: AlertType;
    acknowledged: boolean;
    triggeredAt: Time;
    plateNumber: string;
    message: string;
    severity: AlertSeverity;
    cameraId: bigint;
}): {
    organizationId: bigint;
    alertType: _AlertType;
    acknowledged: boolean;
    triggeredAt: _Time;
    plateNumber: string;
    message: string;
    severity: _AlertSeverity;
    cameraId: bigint;
} {
    return {
        organizationId: value.organizationId,
        alertType: to_candid_AlertType_n9(_uploadFile, _downloadFile, value.alertType),
        acknowledged: value.acknowledged,
        triggeredAt: value.triggeredAt,
        plateNumber: value.plateNumber,
        message: value.message,
        severity: to_candid_AlertSeverity_n11(_uploadFile, _downloadFile, value.severity),
        cameraId: value.cameraId
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertType): {
    blacklist: null;
} | {
    whitelist: null;
} | {
    overspeed: null;
} {
    return value == AlertType.blacklist ? {
        blacklist: null
    } : value == AlertType.whitelist ? {
        whitelist: null
    } : value == AlertType.overspeed ? {
        overspeed: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == AlertSeverity.low ? {
        low: null
    } : value == AlertSeverity.high ? {
        high: null
    } : value == AlertSeverity.critical ? {
        critical: null
    } : value == AlertSeverity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CameraStatus): {
    offline: null;
} | {
    recording: null;
} | {
    online: null;
} {
    return value == CameraStatus.offline ? {
        offline: null
    } : value == CameraStatus.recording ? {
        recording: null
    } : value == CameraStatus.online ? {
        online: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CameraType): {
    onvif: null;
} | {
    rtsp: null;
} | {
    hikvision: null;
} {
    return value == CameraType.onvif ? {
        onvif: null
    } : value == CameraType.rtsp ? {
        rtsp: null
    } : value == CameraType.hikvision ? {
        hikvision: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRoleType): {
    admin: null;
} | {
    operator: null;
} | {
    viewer: null;
} {
    return value == UserRoleType.admin ? {
        admin: null
    } : value == UserRoleType.operator ? {
        operator: null
    } : value == UserRoleType.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrganizationPlan): {
    pro: null;
} | {
    enterprise: null;
} | {
    free: null;
} {
    return value == OrganizationPlan.pro ? {
        pro: null
    } : value == OrganizationPlan.enterprise ? {
        enterprise: null
    } : value == OrganizationPlan.free ? {
        free: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ANPRLogStatus): {
    alert: null;
} | {
    whitelisted: null;
} | {
    identified: null;
} {
    return value == ANPRLogStatus.alert ? {
        alert: null
    } : value == ANPRLogStatus.whitelisted ? {
        whitelisted: null
    } : value == ANPRLogStatus.identified ? {
        identified: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    bus: null;
} | {
    car: null;
} | {
    truck: null;
} | {
    motorcycle: null;
} | {
    other: null;
} {
    return value == VehicleType.bus ? {
        bus: null
    } : value == VehicleType.car ? {
        car: null
    } : value == VehicleType.truck ? {
        truck: null
    } : value == VehicleType.motorcycle ? {
        motorcycle: null
    } : value == VehicleType.other ? {
        other: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
